/**
 * Спільний опис рядків демо-замовлень журналу (телефон → авто/VIN із AUTO.RIA).
 * Усі унікальні VIN із наданого списку; дублікати в копіпасті VW/Tiguan та Passat усунені (два VW — два різні коди в рядках).
 */

const DEMO_ORDER_ROWS = [
  {
    client: 'Олександр Мельник',
    phone: '0671000421',
    car: 'Audi A7',
    plate: 'KA 8842 BK',
    vin: 'WAUJFAFH9DN012904',
    urgent: true,
    payment: 'Готівка',
    picks: ['Заміна комплекту ГРМ з помпою'],
  },
  {
    client: 'Ігор Коваленко',
    phone: '0671000422',
    car: 'Škoda Rapid',
    plate: 'BI 7711 AA',
    vin: 'TMBHM61ZXB2138045',
    urgent: false,
    payment: 'Картка',
    picks: ['Заміна осушувача кондиціонера', 'Заміна комплекту свічок запалювання'],
  },
  {
    client: 'Марія Петренко',
    phone: '0671000423',
    car: 'Tesla Model 3',
    plate: 'BK 9910 BC',
    vin: '5YJ3E1EC7NF274148',
    urgent: true,
    payment: 'Готівка',
    picks: ['Заміна радіатора пічки'],
  },
  {
    client: 'Дмитро Шевченко',
    phone: '0671000424',
    car: 'Volkswagen Tiguan',
    plate: 'AA 1022 CE',
    vin: 'WVGZZZ5NZJW862570',
    urgent: false,
    payment: 'Готівка',
    picks: ['Заміна повітряного фільтра двигуна', 'Заміна датчика положення дросельної заслінки'],
  },
  {
    client: 'Анна Лисенко',
    phone: '0671000425',
    car: 'Audi Q5',
    plate: 'AX 5588 IK',
    vin: 'WA1LFAFP3EA017182',
    urgent: true,
    payment: 'Картка',
    picks: ['Заміна переднього амортизатора (газо-масляний)'],
  },
  {
    client: 'Віталій Бондарчук',
    phone: '0671000426',
    car: 'Škoda Octavia',
    plate: 'KE 6644 KK',
    vin: 'TMBHT61Z9C2099758',
    urgent: false,
    payment: 'Готівка',
    picks: ['Заміна генератора 180A'],
  },
  {
    client: 'Сергій Ткаченко',
    phone: '0671000427',
    car: 'Toyota Highlander',
    plate: 'TT 7733 HH',
    vin: '5TDLB3CH80S064195',
    urgent: false,
    payment: 'Готівка',
    picks: ['Прокачування гальмівної системи (рідина DOT4)'],
  },
  {
    client: 'Роман Гаврилюк',
    phone: '0671000428',
    car: 'Mercedes-Benz S-Class',
    plate: 'CE 4499 CB',
    vin: 'WDD2221591A341700',
    urgent: true,
    payment: 'Готівка',
    picks: ['Заміна переднього крила (ліве)', 'Набір витратників під кузовні роботи (шліфкруги P80)'],
  },
  {
    client: 'Наталія Сидоренко',
    phone: '0671000429',
    car: 'Nissan X-Trail',
    plate: 'KX 3321 KK',
    vin: 'JN1TCAT32U0123590',
    urgent: false,
    payment: 'Картка',
    picks: ['Встановлення та регулювання капоту (алюміній)'],
  },
  {
    client: 'Євген Мороз',
    phone: '0671000430',
    car: 'BMW 5 Series',
    plate: 'II 9001 IK',
    vin: 'WBACV61030LJ66296',
    urgent: false,
    payment: 'Готівка',
    picks: ['Заміна комплекту ГРМ з помпою', 'Заміна повітряного фільтра двигуна'],
  },
  {
    client: 'Катерина Вовк',
    phone: '0671000431',
    car: 'Volkswagen Passat Variant',
    plate: 'CH 7712 XP',
    vin: 'WVGZZZ7PZHD032349',
    urgent: false,
    payment: 'Картка',
    picks: ['Заміна осушувача кондиціонера'],
  },
];

module.exports = { DEMO_ORDER_ROWS };
